In [1]:
import pandas as pd

In [39]:
data = pd.read_csv("tweets.csv") 
data.head()

,user,fullname,tweet-id,timestamp,url,likes,replies,retweets,text,html
0,julia_vaingurt,Julia Vaingurt,746855460402302976,2016-06-25 23:59:52,/julia_vaingurt/status/746855460402302976,0,0,0,Bitcoin: Pissed-off customers sue GAW Miners i...,"<p class=""TweetTextSize js-tweet-text tweet-te..."
1,haj1106,hunter,746855393695924224,2016-06-25 23:59:36,/haj1106/status/746855393695924224,0,0,0,I'm not gone lie I be staring at pplwhat btc's...,"<p class=""TweetTextSize js-tweet-text tweet-te..."
2,rimbit,Rimbit ➡,746855315589652480,2016-06-25 23:59:17,/rimbit/status/746855315589652480,0,0,0,Did you miss Beyond Bitcoin Hangout? I CANNOT ...,"<p class=""TweetTextSize js-tweet-text tweet-te..."
3,coinstories,Coin Stories,746855306026680321,2016-06-25 23:59:15,/coinstories/status/746855306026680321,0,0,0,What are the merits and risks of investing in ...,"<p class=""TweetTextSize js-tweet-text tweet-te..."
4,bitcointonic,Julia Edling,746855274816798720,2016-06-25 23:59:08,/bitcointonic/status/746855274816798720,1,0,1,Hash Ocean #Bitcoin Cloud Mining №1 in the wor...,"<p class=""TweetTextSize js-tweet-text tweet-te..."

In [40]:
desc = data.describe()
del data['html'];
del data['url'];
data.head()

,user,fullname,tweet-id,timestamp,likes,replies,retweets,text
0,julia_vaingurt,Julia Vaingurt,746855460402302976,2016-06-25 23:59:52,0,0,0,Bitcoin: Pissed-off customers sue GAW Miners i...
1,haj1106,hunter,746855393695924224,2016-06-25 23:59:36,0,0,0,I'm not gone lie I be staring at pplwhat btc's...
2,rimbit,Rimbit ➡,746855315589652480,2016-06-25 23:59:17,0,0,0,Did you miss Beyond Bitcoin Hangout? I CANNOT ...
3,coinstories,Coin Stories,746855306026680321,2016-06-25 23:59:15,0,0,0,What are the merits and risks of investing in ...
4,bitcointonic,Julia Edling,746855274816798720,2016-06-25 23:59:08,1,0,1,Hash Ocean #Bitcoin Cloud Mining №1 in the wor...

In [47]:
import numpy as np
data['timestamp'] = pd.to_datetime(data['timestamp']).astype(int)
data.head()

,user,fullname,tweet-id,timestamp,likes,replies,retweets,text
0,julia_vaingurt,Julia Vaingurt,746855460402302976,1466899192,0,0,0,Bitcoin: Pissed-off customers sue GAW Miners i...
1,haj1106,hunter,746855393695924224,1466899176,0,0,0,I'm not gone lie I be staring at pplwhat btc's...
2,rimbit,Rimbit ➡,746855315589652480,1466899157,0,0,0,Did you miss Beyond Bitcoin Hangout? I CANNOT ...
3,coinstories,Coin Stories,746855306026680321,1466899155,0,0,0,What are the merits and risks of investing in ...
4,bitcointonic,Julia Edling,746855274816798720,1466899148,1,0,1,Hash Ocean #Bitcoin Cloud Mining №1 in the wor...

In [38]:
#data['timestamp'] = pd.to_datetime(data['timestamp'])
#data['timestamp'] = pd.to_timedelta(data['timestamp'], unit='ns')
#data.head()

,user,fullname,tweet-id,timestamp,likes,replies,retweets,text
0,julia_vaingurt,Julia Vaingurt,746855460402302976,16977 days 23:59:52,0,0,0,Bitcoin: Pissed-off customers sue GAW Miners i...
1,haj1106,hunter,746855393695924224,16977 days 23:59:36,0,0,0,I'm not gone lie I be staring at pplwhat btc's...
2,rimbit,Rimbit ➡,746855315589652480,16977 days 23:59:17,0,0,0,Did you miss Beyond Bitcoin Hangout? I CANNOT ...
3,coinstories,Coin Stories,746855306026680321,16977 days 23:59:15,0,0,0,What are the merits and risks of investing in ...
4,bitcointonic,Julia Edling,746855274816798720,16977 days 23:59:08,1,0,1,Hash Ocean #Bitcoin Cloud Mining №1 in the wor...

In [6]:
coinData = pd.read_csv("bitcoin-historical-data/bitstampUSD_1-min_data_2012-01-01_to_2019-08-12.csv")
coinData.head()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1325317920,4.39,4.39,4.39,4.39,0.455581,2.0,4.39
1,1325317980,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1325318040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1325318100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1325318160,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
from datetime import datetime

In [12]:
now = datetime.now()
timestamp = datetime.timestamp(now)
print("timestamp =", int(timestamp))
timestamp = 1545730073
dt_object = datetime.fromtimestamp(timestamp)
print(str(dt_object))

timestamp = 1573411688
2018-12-25 02:27:53

In [15]:
pd.to_datetime(coinData['Timestamp']).apply(lambda x: x.date())

0          1970-01-01
1          1970-01-01
2          1970-01-01
3          1970-01-01
4          1970-01-01
              ...
3997692    1970-01-01
3997693    1970-01-01
3997694    1970-01-01
3997695    1970-01-01
3997696    1970-01-01
Name: Timestamp, Length: 3997697, dtype: object

In [54]:
coinData = coinData.rename(columns = {'Timestamp':'timestamp'})
#coinData.info()
result = pd.merge(data, coinData, how='left', on=['timestamp'])
result.head()

,user,fullname,tweet-id,timestamp,likes,replies,retweets,text,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,julia_vaingurt,Julia Vaingurt,746855460402302976,1466899192,0,0,0,Bitcoin: Pissed-off customers sue GAW Miners i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,haj1106,hunter,746855393695924224,1466899176,0,0,0,I'm not gone lie I be staring at pplwhat btc's...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,rimbit,Rimbit ➡,746855315589652480,1466899157,0,0,0,Did you miss Beyond Bitcoin Hangout? I CANNOT ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,coinstories,Coin Stories,746855306026680321,1466899155,0,0,0,What are the merits and risks of investing in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bitcointonic,Julia Edling,746855274816798720,1466899148,1,0,1,Hash Ocean #Bitcoin Cloud Mining №1 in the wor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN